esphome:
  name: volkszahler-lora-gateway
  friendly_name: Volkszähler LoRa Gateway

esp32:
  board: ttgo-lora32-v21
  framework:
    type: arduino

# Enable logging
logger:
  level: DEBUG

# Enable Home Assistant API
api:

# OTA updates
ota:
  - platform: esphome

# WiFi Configuration
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  
  ap:
    ssid: "LoRa-Gateway-Fallback"
    password: "fallback123"

captive_portal:

# Web server
web_server:
  port: 80

# Time synchronization
time:
  - platform: homeassistant
    id: homeassistant_time

# I2C bus for display
i2c:
  sda: 21
  scl: 22
  frequency: 400kHz

# Fonts for display (using Google Fonts)
font:
  - file:
      type: gfonts
      family: Roboto Mono
      weight: 700
    id: font_large
    size: 20
  - file:
      type: gfonts
      family: Roboto Mono
      weight: 400
    id: font_medium
    size: 14
  - file:
      type: gfonts
      family: Roboto Mono
      weight: 400
    id: font_small
    size: 10

# OLED Display configuration
display:
  - platform: ssd1306_i2c
    model: "SSD1306 128x64"
    address: 0x3C
    rotation: 0
    id: oled_display
    pages:
      # Page 1: Status
      - id: page_status
        lambda: |-
          // Title
          it.print(64, 0, id(font_small), TextAlign::TOP_CENTER, "LORA GATEWAY");
          it.line(0, 10, 127, 10);
          
          // Waiting for data
          it.print(64, 25, id(font_medium), TextAlign::CENTER, "Waiting for");
          it.print(64, 40, id(font_medium), TextAlign::CENTER, "LoRa data...");
          
          // Power placeholder
          char power_str[20];
          snprintf(power_str, sizeof(power_str), "Power: %.0fW", id(meter_power).state);
          it.print(0, 54, id(font_small), power_str);
          
      # Page 2: Network Info
      - id: page_network
        lambda: |-
          it.print(64, 0, id(font_small), TextAlign::TOP_CENTER, "NETWORK INFO");
          it.line(0, 10, 127, 10);
          
          // Signal strength
          char wifi_str[30];
          snprintf(wifi_str, sizeof(wifi_str), "WiFi: %.0f dBm", id(wifi_signal_sensor).state);
          it.print(0, 20, id(font_small), wifi_str);
          
          // Uptime
          char uptime_str[30];
          snprintf(uptime_str, sizeof(uptime_str), "Uptime: %.0f s", id(uptime_sensor).state);
          it.print(0, 32, id(font_small), uptime_str);
          
          // Placeholder for LoRa status
          it.print(0, 44, id(font_small), "LoRa: Waiting...");
          
    update_interval: 5s  # Update display every 5 seconds

# Display page rotation
interval:
  - interval: 10s
    then:
      - display.page.show_next: oled_display
      - component.update: oled_display

# Basic sensors for display
sensor:
  # WiFi Signal
  - platform: wifi_signal
    name: "WiFi Signal"
    id: wifi_signal_sensor
    update_interval: 60s
    
  # Uptime
  - platform: uptime
    name: "Uptime"
    id: uptime_sensor
    update_interval: 10s
    
  # Template sensors for meter data (will be updated via MQTT or custom component later)
  - platform: template
    name: "Smart Meter Power"
    id: meter_power
    unit_of_measurement: "W"
    device_class: power
    state_class: measurement
    accuracy_decimals: 1
    icon: "mdi:flash"
    lambda: |-
      return 0;  // Placeholder
    
  - platform: template
    name: "Smart Meter Total Consumption"
    id: meter_consumption
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 3
    icon: "mdi:counter"
    lambda: |-
      return 0;  // Placeholder
    
  - platform: template
    name: "Smart Meter Total Generation"
    id: meter_generation
    unit_of_measurement: "kWh"
    device_class: energy
    state_class: total_increasing
    accuracy_decimals: 3
    icon: "mdi:solar-power"
    lambda: |-
      return 0;  // Placeholder
    
  - platform: template
    name: "Smart Meter Battery Voltage"
    id: meter_battery
    unit_of_measurement: "V"
    device_class: voltage
    state_class: measurement
    accuracy_decimals: 2
    icon: "mdi:battery"
    lambda: |-
      return 3.7;  // Placeholder